name: Test
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run kLint check
        run: |
          ./gradlew ktlintCheck

      - name: Run testing
        run: |
          ./gradlew test

      - name: Add coverage report
        uses: madrapps/jacoco-report@v1.2
        continue-on-error: true
        with:
          title: Unit and integration test coverage
          paths: ${{ github.workspace }}/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 80